### ISSUE TITLE
Problem with program from book

### ISSUE THREAD

**Issue by KryspinTrawnik** [KryspinTrawnik/Hello.World#1]
namespace Przywitanie1
{
    class Program
    {
        static void Main(string[] args)
        {
            const int komputery = 24;
            int studenci = 48;
            double wynik;
            Console.WriteLine("Podaj liczbe studnetow:");
           # studenci = Convert.ToInt32(Console.ReadLine()); /*this is the line which I took from the book, when it is on program doesn't work*/
            wynik = (double)studenci / komputery;
            Console.WriteLine(wynik);
            Console.ReadKey();

        }
    }
}

**Comment by senaszel** [comment]
Na moje oko to ten kod nie dziala przez kratke przed Convertem ;)
